name: flutter_portfolio
description: My dev portfolio. I decided to update it into a flutter web app to showcase firsthand my knowledge with flutter using flutter itself.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_lints: 2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/portfolio/